### ISSUE TITLE
DQN-Vissim

### ISSUE THREAD

**Issue by bobo123bobo321** [Linging/Traffic-Signal-Control#1]
Thank you for sharing. Thank you very much, but I have a problem that has been bothering for a long time. The following error will always occur:
Summary.append(tr.GetResult(600, "TRAVELTIME", "", 0))
AttributeError: 'NoneType' object has no attribute 'GetResult'.
Leading to the running of the test set, please have a solution, look forward to your reply.

**Comment by Linging** [comment]
Sry for waiting so long, I did not have the same problem. If you are solving this problem, maybe you could check the vehicle numbers in simulation. I suspect that if no vehicles on the net at a moment, VISSIM will return null if you want to get the information of running cars. By the way, vissim will return abnormal data sometimes and I don't konw the reason, and its simulation speed is slow , so I start to use FLOW which is a cool traffic simulation framework developed by Cathy Wu.
